print (' _____\t\t\t\t____\t\t____\t\t|    |')
print ('|     |\t\t|\t\t    |\t\t    |\t\t|____|')
print ('|     |\t\t|\t\t____|\t\t _ _|\t\t     |')
print ('|     |\t\t|\t\t|\t\t    |\t\t     |')
print ('|_____|\t\t|\t\t|____\t\t____|\t\t     |')
