print(' ____ \t\t\t___ \t___\t')
print('|    |\t\t|\t   |\t   |\t   |    |')
print('|    |\t\t|\t___|\t___|\t   |____|')
print('|    |\t\t|\t|   \t   |\t        |')
print('|____|\t\t|\t|___\t___|\t        |')
